//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PEditor.rc
//
#define IDC_EDIT_MESH_CTLPT             1009
#define IDC_EDIT_MESH                   1010
#define IDC_SMOOTH_SHADE                1011
#define IDC_SNUM_U                      1013
#define IDC_EDIT_MESH_VERT              1014
#define IDC_EDIT_MESH_FACE              1015
#define IDC_SHOW_MESH                   1016
#define IDC_TEXTURE                     1017
#define IDC_TRANSPARENT                 1018
#define IDC_SNUM_V                      1019
#define IDC_SHOW_CTRL_PT                1020
#define IDC_SNUM_W                      1020
#define IDC_WIRE_FRAME                  1021
#define IDC_FLAT_SHADE                  1022
#define IDC_CTRL_PT_SIZE                1023
#define IDC_REFINE_U                    1024
#define IDC_REFINE_V                    1025
#define IDC_ELEVATE_DEGREE              1025
#define IDC_MESH_NUM_VERT               1029
#define IDC_MESH_NUM_FACE               1030
#define IDC_ELEVATE_DEG_U               1030
#define IDC_MESH_REF_NAME               1031
#define IDC_MESH_CLASS_NAME             1031
#define IDC_ELEVATE_DEG_V               1031
#define IDC_MODIFY_KNOT_CLAMPED_U       1032
#define IDC_MODIFY_KNOT_UNCLAMPED_U     1033
#define IDC_MODIFY_KNOT_CLAMPED_V       1034
#define IDC_MODIFY_KNOT_UNCLAMPED_V     1035
#define IDD_EDIT_MESH_DLG               5000
#define IDW_PARAM_SPACE                 5000
#define IDC_CONE_ANGLE                  5002
#define IDC_CONE_DEFORM_LEFT_SLIDER     5003
#define IDC_CONE_DEFORM_RIGHT_SLIDER    5004
#define IDD_EDIT_NURBS_DLG              5004
#define IDD_EDIT_SRF_DLG                5004
#define IDC_CONE_DEFORM_ANGLE1          5005
#define IDD_EDIT_VOL_DLG                5005
#define IDC_CONE_DEFORM_ANGLE2          5006
#define IDD_EDIT_CRV_DLG                5006
#define IDC_CYLINDER_RAD                5007
#define IDD_EDIT_SWP_DLG                5007
#define IDC_CYLINDER_DEFORM_LEFT_SLIDER 5008
#define IDC_EDIT_RANGE_U                5008
#define IDD_EDIT_BLEND_SRF_DLG          5008
#define IDC_CYLINDER_DEFORM_RIGHT_SLIDER 5009
#define IDC_EDIT_RANGE_V                5009
#define IDC_CYLINDER_DEFORM_ANGLE1      5010
#define IDD_ADD_MTL_DLG                 5010
#define IDC_CYLINDER_DEFORM_ANGLE2      5011
#define IDD_EDIT_CONTACT_CRV_DLG        5011
#define IDC_EDIT_RANGE_SLIDER_U         5012
#define IDC_EDIT_RANGE_SLIDE            5013
#define IDC_EDIT_RANGE_SLIDER_V         5013
#define IDC_MTRL_LIST                   5018
#define IDC_ADD_MATERIAL                5019
#define IDC_SNUM_U_SPIN                 5020
#define IDC_EDIT_MATERIAL               5020
#define IDC_SNUM_V_SPIN                 5021
#define IDC_DEL_MATERIAL                5021
#define IDC_MESH_NAME                   5022
#define IDC_SNUM_W_SPIN                 5022
#define IDC_EDIT_OP_LIST                5023
#define IDC_EDIT_TOOL_LIST              5023
#define IDC_APPLY_EDIT_TOOL             5024
#define IDC_MESH_TRANS_X                5025
#define IDC_EDIT_MESH_ARB_VERT          5026
#define IDC_HEIGHT_MAP_TYPE             5027
#define IDC_HEIGHT_MAP_TYPE_PLANE       5028
#define IDC_HEIGHT_MAP_TYPE_ORIGIN      5029
#define IDC_VERT_GEOM_ALL_PLANE         5030
#define IDC_VERT_GEOM_ALL_VERT          5031
#define IDC_VERT_GEOM_ALL_APPROX        5032
#define IDC_NURBS_NAME                  5032
#define IDC_MESH_SELECT_REGION_FREE     5033
#define IDC_MESH_TRANS_Y                5034
#define IDC_MESH_TRANS_Z                5035
#define IDC_MESH_ROT_X                  5036
#define IDC_MESH_ROT_Y                  5037
#define IDC_MESH_ROT_Z                  5038
#define IDC_MESH_SCL_X                  5039
#define IDC_MESH_SCL_Y                  5040
#define IDC_MESH_SCL_Z                  5041
#define IDC_MESH_SELECT_REGION_RECT     5042
#define IDC_INSERT_RAGDOLL              5042
#define IDC_PATCH_TYPE_PN               5045
#define IDC_PATCH_TYPE_EXT_PN           5046
#define IDC_BLEND_OFFSET_E0             5047
#define IDC_BLEND_OFFSET_E1             5048
#define IDC_BLEND_OFFSET_E2             5049
#define IDC_PATCH_TYPE_FLAT             5050
#define IDC_BLEND_OFFSET                5051
#define IDC_SEW_ANGLE_TOLER             5053
#define IDC_SEW_DIST_TOLER              5054
#define IDC_SEW_MESH                    5055
#define IDC_SWP_RENDER_TYPE_SRF         5056
#define IDC_SWP_RENDER_TYPE_PLN         5057
#define IDC_SWP_PLN_WIDTH               5058
#define IDC_SWP_PLN_HEIGHT              5059
#define IDC_BRUSH_TOOL_RAD              5059
#define IDC_ISO_U_MIN                   5060
#define IDC_EDIT_RGN_DIST               5060
#define IDC_ISO_U_MAX                   5061
#define IDC_TRANSPARENCY                5061
#define IDC_ISO_V_MIN                   5062
#define IDC_DIST_GEODESIC               5062
#define IDC_ISO_V_MAX                   5063
#define IDC_RADIO2                      5063
#define IDC_DIST_TOPOLOGY               5063
#define IDC_EDIT1                       5063
#define IDC_AMBIENT_GREEN               5063
#define IDC_ISO_W_MIN                   5064
#define IDC_EDIT2                       5064
#define IDC_AMBIENT_RED                 5064
#define IDC_DIST_EUCLID                 5064
#define IDC_ISO_W_MAX                   5065
#define IDC_EDIT3                       5065
#define IDC_AMBIENT_BLUE                5065
#define IDC_EDIT4                       5066
#define IDC_DIFFUSE_GREEN               5066
#define IDC_EDIT5                       5067
#define IDC_DIFFUSE_RED                 5067
#define IDC_EDIT6                       5068
#define IDC_DIFFUSE_BLUE                5068
#define IDC_EDIT7                       5069
#define IDC_SPECULAR_GREEN              5069
#define IDC_EDIT8                       5070
#define IDC_SPECULAR_RED                5070
#define IDC_EDIT9                       5071
#define IDC_SPECULAR_BLUE               5071
#define IDC_MTL_NAME                    5072
#define IDC_TEX_FILE_NAME               5073
#define IDC_OPEN_DIFFUSE_TEXTURE        5074
#define IDC_CNVRT_BZR_FORM              5074
#define IDC_MTL_RANDOM                  5077
#define IDC_CNVRT_BSP_FORM              5077
#define IDC_CNVRT_BSP_FORM2             5078
#define IDC_REVERSE_DIRECTION           5078
#define IDC_MODIFY_KNOT_CLAMPED         5080
#define IDC_MODIFY_KNOT_UNCLAMPED       5081
#define IDC_RENDER_AS_LINE              5083
#define IDC_SHOW_EDIT_BNDRY_APPROX      5084
#define IDC_SHOW_EDIT_BNDRY_EXACT       5085
#define IDC_COLLISION_CHECK             5086
#define IDC_SHOW_EDIT_BNDRY_EXACT2      5087
#define IDC_COLLISION_FREE              5087
#define IDC_AMBIENT_COLOR               5091
#define IDC_DIFFUSE_COLOR               5092
#define IDC_COLOR_BTN3                  5093
#define IDC_SPECULAR_COLOR              5093
#define IDC_SHOW_2D_VIEW                5094
#define IDC_SET_AS_START_MESH2          5096
#define IDC_PRT_SCN                     5097

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        5013
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         5098
#define _APS_NEXT_SYMED_VALUE           5002
#endif
#endif
